import {colType} from '@cm/types/col-types'
import {colTypeStr} from '@cm/types/types'

type sateiTableCompartionCol = {
  label: string
  type: colTypeStr
  bqKeys: {proto: string; upass: string}
}
export const sateiTableCompartionCols: sateiTableCompartionCol[] = [
  {
    label: `査定ID`,
    bqKeys: {proto: `Assessment_ID`, upass: 'sateiID'},
    type: `string`,
  },
  {
    label: `車種名`,
    bqKeys: {proto: `Model_name`, upass: 'modelName'},
    type: `string`,
  },
  {
    label: `ブランド名`,
    bqKeys: {proto: `brand_name`, upass: 'brandName'},
    type: `string`,
  },
  {
    label: `通称型式`,
    bqKeys: {proto: `Model`, upass: 'type'},
    type: `string`,
  },
  {
    label: `カラー`,
    bqKeys: {proto: `Body_color`, upass: 'exteriorColor'},
    type: `string`,
  },
  {
    label: `車台番号`,
    bqKeys: {proto: `Barracks`, upass: 'chassisNumber'},
    type: `string`,
  },
  {
    label: `グレード`,
    bqKeys: {proto: `Grade_name`, upass: 'grade'},
    type: `string`,
  },
  {
    label: `モデル年式`,
    bqKeys: {proto: `Model_year`, upass: 'modelYear'},
    type: `string`,
  },
  {
    label: 'ナンバー_地名',
    bqKeys: {proto: 'Number_Place_name', upass: 'landAffairsName'},
    type: `string`,
  },
  {
    label: 'ナンバー_分類番号',
    bqKeys: {proto: 'Number_classification_number', upass: 'registrationClassNumber'},
    type: `string`,
  },
  {
    label: 'ナンバー_ひらがな',
    bqKeys: {proto: 'Number_Hiragana', upass: 'registrationKana'},
    type: `string`,
  },
  {
    label: 'ナンバー',
    bqKeys: {proto: 'number', upass: 'registrationSerialNumber'},
    type: `string`,
  },
  {
    label: '車寸（長さ）',
    type: `float`,

    bqKeys: {proto: 'Vehicle_length', upass: 'length'},
  },
  {
    label: '車寸（幅）',
    type: `float`,
    bqKeys: {proto: 'Vehicle_width', upass: 'width'},
  },
  {
    label: '車寸（高さ）',
    type: `float`,
    bqKeys: {proto: 'Vehicle_height', upass: 'height'},
  },
  {
    label: '入庫予定日',
    type: `date`,
    bqKeys: {proto: 'Scheduled_arrival_date', upass: 'pickupScheduledDate'},
  },
]

export const sateiColOrigin: colType[] = [
  {id: 'Assessment_ID', type: 'string', label: '査定ID'},
  {id: 'QR_reading_or_not', type: 'string', label: 'QR読取有無'},
  {id: 'Approval_state', type: 'string', label: '承認状態'},
  {id: 'Latest_assessment_price', type: 'string', label: '最新査定価格'},
  {id: 'Malary_profit_correction_after_price', type: 'string', label: '粗利補正後価格'},
  {id: 'Model_specification_No', type: 'string', label: '型式指定No'},
  {id: 'Classic_NO', type: 'string', label: '類別No'},
  {id: 'Country_name', type: 'string', label: '国名'},
  {id: 'brand_name', type: 'string', label: 'ブランド名'},
  {id: 'Model_name', type: 'string', label: '車種名'},
  {id: 'Model_cycle_name', type: 'string', label: 'モデルサイクル名'},
  {id: 'First_registration_year_1', type: 'string', label: '初度登録年(西暦)'},
  {id: 'First_registration_year_2', type: 'string', label: '初度登録年(和暦)'},
  {id: 'Initial_registration_date', type: 'string', label: '初度登録年月'},
  {id: 'Model', type: 'string', label: '型式(エンジン記号付)'},
  {id: 'Common_name_model', type: 'string', label: '通称型式'},
  {id: 'Certified_type', type: 'string', label: '認定型式'},
  {id: 'Grade_name', type: 'string', label: 'グレード名'},
  {id: 'Mission_name', type: 'string', label: 'ミッション名'},
  {id: 'Capacity', type: 'string', label: '定員'},
  {id: 'Door_name', type: 'string', label: 'ドア名'},
  {id: 'Displacement', type: 'string', label: '排気量'},
  {id: 'Driving', type: 'string', label: '駆動'},

  {id: 'handle', type: 'string', label: 'ハンドル'},
  {id: 'Category_domestic_or_import', type: 'string', label: '区分(国産/輸入)'},
  {id: 'Import_category', type: 'string', label: '輸入区分'},
  {id: 'Number_Place_name', type: 'string', label: 'ナンバー_地名'},
  {id: 'Number_classification_number', type: 'string', label: 'ナンバー_分類番号'},
  {id: 'Number_Hiragana', type: 'string', label: 'ナンバー_ひらがな'},
  {id: 'number', type: 'string', label: 'ナンバー'},
  {id: 'Barracks', type: 'string', label: '車台番号'},
  {id: 'Date_of_registration_date_issued', type: 'string', label: '登録年月日/交付年月日'},
  {id: 'Vehicle_inspection_year', type: 'string', label: '車検(年)'},
  {id: 'Vehicle_inspection_month', type: 'string', label: '車検(月)'},
  {id: 'Vehicle_inspection_date', type: 'string', label: '車検満了日'},
  {id: 'Owner_Name', type: 'string', label: '所有者_氏名又は名称'},
  // {id: 'Owner_Address', type:'string', label: '所有者_住所'},
  {id: 'User_Name', type: 'string', label: '使用者_氏名又は名称'},
  // {id: 'User_Address', type:'string', label: '使用者_住所'},
  {id: 'Serial_NO', type: 'string', label: 'シリアルNo'},
  {id: 'Recycling_deposit_flag', type: 'string', label: 'リサイクル預託金フラグ'},
  {id: 'Shredder_dust_fee', type: 'string', label: 'シュレッダーダスト料金'},
  {id: 'Airbag_fee_fee', type: 'string', label: 'エアバック類料金'},
  {id: 'Freon_fee', type: 'string', label: 'フロン類料金'},
  {id: 'Information_management_fee', type: 'string', label: '情報管理料金'},
  {id: 'Total_recycling_deposits', type: 'string', label: 'リサイクル預託金合計'},
  {id: 'Car_history', type: 'string', label: '車歴'},
  {id: 'Body_color', type: 'string', label: '車体色'},
  {id: 'Color_based_name', type: 'string', label: '色系統名称'},
  {id: 'Color_code', type: 'string', label: 'カラーコード'},
  {id: 'Interior_color', type: 'string', label: '内装色'},
  {id: 'Mileage', type: 'string', label: '走行距離'},
  {id: 'Mileage_unit', type: 'string', label: '走行距離単位'},
  {id: 'sunroof', type: 'string', label: 'サンルーフ'},
  {id: 'Leather_seat', type: 'string', label: 'レザーシート'},
  {id: 'Navi_yes_or_no', type: 'string', label: 'ナビ(有/無)'},
  {id: 'Display_type', type: 'string', label: 'ディスプレイタイプ'},
  {id: 'Navigation', type: 'string', label: 'ナビメディア'},
  {id: 'Navi_remarks', type: 'string', label: 'ナビ備考'},
  {id: 'Interior_state', type: 'string', label: '内装状態'},
  {id: 'institution', type: 'string', label: '機関'},
  {id: 'Electrical_equipment', type: 'string', label: '電装'},
  {id: 'fuel', type: 'string', label: '燃料'},

  {id: 'Evaluation_points', type: 'string', label: '評価点'},

  {id: 'Store_name', type: 'string', label: '店舗名'},
  {id: 'Assessment_person_in_charge', type: 'string', label: '査定担当者'},
  {id: 'Model_year', type: 'string', label: 'モデル年式'},

  // {id: 'Catalog_color', type:'string', label: 'カタログカラー'}, //入ってない車がある
  // {id: 'Color_change', type:'string', label: '色替え'},
  // {id: 'Interior_equipment_consideration', type:'string', label: '内装備考'},
  // {id: 'Unknown_mileage_flag', type:'string', label: '走行距離不明フラグ'},
  // {id: 'Meter_exchange_distance', type:'string', label: 'メーター交換距離'},
  // {id: 'Meter_exchange_distance_unit', type:'string', label: 'メーター交換距離単位'},
  // {id: 'Meter_tampering', type:'string', label: 'メーター改竄'},
  // {id: 'Next_purchase_car', type:'string', label: '次期購入車'},
  // {id: 'Scheduled_arrival_date', type:'string', label: '入庫予定日'},
  // {id: 'Wound_information', type:'string', label: '傷情報'},
  // {id: 'Whether_or_not_the_front_tire_size_is_changed', type:'string', label: 'フロントタイヤサイズ変更有無'},
  // {id: 'Front_tire_size_before_change', type:'string', label: '変更前フロントタイヤサイズ'},
  // {id: 'Changed_front_tire_size', type:'string', label: '変更後フロントタイヤサイズ'},
  // {id: 'Rear_tire_size_change', type:'string', label: 'リアタイヤサイズ変更有無'},
  // {id: 'Before_the_rear_tire_size', type:'string', label: '変更前リアタイヤサイズ'},
  // {id: 'Rear_tire_size_after_change', type:'string', label: '変更後リアタイヤサイズ'},
  // {id: 'Right_front_tire', type:'string', label: '右前タイヤ'},
  // {id: 'Left_front_tire', type:'string', label: '左前タイヤ'},
  // {id: 'Right_and_right_tires', type:'string', label: '右後タイヤ'},
  // {id: 'Left_tire', type:'string', label: '左後タイヤ'},
  // {id: 'Preliminary_tires', type:'string', label: '予備タイヤ有無'},
  // {id: 'Spare_tire', type:'string', label: '予備タイヤ'},
  // {id: 'Wheel_scratch___right_front', type:'string', label: 'ホイールキズ_右前'},
  // {id: 'Wheel_scratch___left_front', type:'string', label: 'ホイールキズ_左前'},
  // {id: 'Wheel_scratch___Right_after', type:'string', label: 'ホイールキズ_右後'},
  // {id: 'Wheel_scratch___left_rear', type:'string', label: 'ホイールキズ_左後'},
  // {id: 'Truck_right_tire_with_right_tires', type:'string', label: 'トラック右タイヤ有無'},
  // {id: 'Truck_right_tire_condition', type:'string', label: 'トラック右タイヤ状態'},
  // {id: 'Truck_left_tire_with_left_tires', type:'string', label: 'トラック左タイヤ有無'},
  // {id: 'Truck_left_tire_condition', type:'string', label: 'トラック左タイヤ状態'},
  // {id: 'Preliminary_truck_tires', type:'string', label: '予備トラックタイヤ有無'},
  // {id: 'Preliminary_truck_tire_condition', type:'string', label: '予備トラックタイヤ状態'},
  // {id: 'Truck_right_tire_wheel_condition', type:'string', label: 'トラック右タイヤホイール状態'},
  // {id: 'Truck_left_tire_wheel_condition', type:'string', label: 'トラック左タイヤホイール状態'},
  // {id: 'Preliminary_truck_tire_wheel_condition', type:'string', label: '予備トラックタイヤホイール状態'},
  // {id: 'Repair_information', type:'string', label: '修復情報'},
  // {id: 'Repair_status_preparation', type:'string', label: '修復状態備考'},
  // {id: 'Remarks_for_the_current_accident', type:'string', label: '事故現状備考'},
  // {id: 'Exterior_evaluation_point', type:'string', label: '外装評価点'},
  // {id: 'Interior_evaluation_point', type:'string', label: '内装評価点'},
  // {id: 'Assessment_evaluation_point', type:'string', label: '査定者評価点'},
  // {id: 'Assessment_exterior_evaluation', type:'string', label: '査定者外装評価'},
  // {id: 'Air_conditioner', type:'string', label: 'エアコン'},
  // {id: 'sales_point', type:'string', label: 'セールスポイント'},
  // {id: 'Restoration_state', type:'string', label: '修復状態'},
  // {id: 'Other_information', type:'string', label: 'その他情報'},

  //   {id: 'Warehouse_status', type:'string', label: '入庫ステータス'},
  //   {id: 'Home_phone_number', type:'string', label: '自宅電話番号'},
  //   {id: 'Home_postal_code', type:'string', label: '自宅郵便番号'},
  //   {id: 'Home_Address', type:'string', label: '自宅住所'},
  //   {id: 'Order_card_No', type:'string', label: '注文書ＮＯ'},
  //   {id: 'SG_client_store_name', type:'string', label: 'SGクライアント店舗名'},
  //   {id: 'Question_1', type:'string', label: '設問1'},
  //   {id: 'Question_type_1', type:'string', label: '設問タイプ1'},
  //   {id: 'Answer_1', type:'string', label: '回答1'},
  //   {id: 'Question_2', type:'string', label: '設問2'},
  //   {id: 'Question_type_2', type:'string', label: '設問タイプ2'},
  //   {id: 'Answer_2', type:'string', label: '回答2'},
  //   {id: 'Question_3', type:'string', label: '設問3'},
  //   {id: 'Question_type_3', type:'string', label: '設問タイプ3'},
  //   {id: 'Answer_3', type:'string', label: '回答3'},
  //   {id: 'Question_4', type:'string', label: '設問4'},
  //   {id: 'Question_type_4', type:'string', label: '設問タイプ4'},
  //   {id: 'Answer_4', type:'string', label: '回答4'},
  //   {id: 'Question_5', type:'string', label: '設問5'},
  //   {id: 'Question_type_5', type:'string', label: '設問タイプ5'},
  //   {id: 'Answer_5', type:'string', label: '回答5'},
  //   {id: 'Question_6', type:'string', label: '設問6'},
  //   {id: 'Question_type_6', type:'string', label: '設問タイプ6'},
  //   {id: 'Answer_6', type:'string', label: '回答6'},
  //   {id: 'Question_7', type:'string', label: '設問7'},
  //   {id: 'Question_type_7', type:'string', label: '設問タイプ7'},
  //   {id: 'Answer_7', type:'string', label: '回答7'},
  //   {id: 'Question_8', type:'string', label: '設問8'},
  //   {id: 'Question_type_8', type:'string', label: '設問タイプ8'},
  //   {id: 'Answer_8', type:'string', label: '回答8'},
  //   {id: 'Question_9', type:'string', label: '設問9'},
  //   {id: 'Question_type_9', type:'string', label: '設問タイプ9'},
  //   {id: 'Answer_9', type:'string', label: '回答9'},
  //   {id: 'Question_10', type:'string', label: '設問10'},
  //   {id: 'Question_type_10', type:'string', label: '設問タイプ10'},
  //   {id: 'Answer_10', type:'string', label: '回答10'},
  //   {id: 'Customer_name', type:'string', label: 'お客様氏名'},
  //   {id: 'Unlocking_ownership', type:'string', label: '所有権解除'},
  //   {id: 'mail_address', type:'string', label: 'メールアドレス'},

  //   {id: 'engine', type:'string', label: 'エンジン'},
  //   {id: 'turbo', type:'string', label: 'ターボ'},
  //   {id: 'shape', type:'string', label: '形状'},
  //   {id: 'Deposit_date', type:'string', label: '預託日'},
  //   {id: 'Liability_from', type:'string', label: '自賠責From'},
  //   {id: 'Liability_to', type:'string', label: '自賠責To'},
  //   {id: 'Motor_model', type:'string', label: '原動機の型式'},
  //   {id: 'Meter_exchange', type:'string', label: 'メーター交換'},
  //   {id: 'Email_reflection_comment', type:'string', label: 'メール反映コメント'},
  //   {id: 'Assessment_reflection_comment', type:'string', label: '査定反映コメント'},
  //   {id: 'Warehouse_status_date', type:'string', label: '入庫ステータス日付'},
  //   {id: 'comment', type:'string', label: 'コメント'},
  //   {id: 'Wholesale_price', type:'string', label: '卸価格'},
  //   {id: 'retail_price', type:'string', label: '小売価格'},
  //   {id: 'Assessment_additional_price_price', type:'string', label: '査定者加減算価格'},
  //   {id: 'Reason_for_adjusting', type:'string', label: '加減算理由'},
  //   {id: 'sales_representative', type:'string', label: '営業担当者'},
  //   {id: 'Desired_assessment_price', type:'string', label: '希望査定価格'},
  //   {id: 'Reason_for_the_desired_assessment_price', type:'string', label: '希望査定価格理由'},
  //   {id: 'PDF_reading_or_not', type:'string', label: 'PDF読取有無'},
  //   {id: 'Tire_punk_repair_kit', type:'string', label: 'タイヤパンク修理キット'},
]

export const sateiBasicCols = []
export const tdIncludeKeys = [
  'Assessment_ID',
  'Latest_assessment_date',
  'QR_reading_or_not',
  'brand_name',
  'Model_name',
  'Model_cycle_name',
  'Model',
  'Common_name_model',
  'Certified_type',
  'Grade_name',
]

export const getUcarTdIncludeCols = () => sateiColOrigin.filter(v => tdIncludeKeys.includes(v.id))
export const getUcarTdExcludeCols = () => sateiColOrigin.filter(v => !tdIncludeKeys.includes(v.id))

export const getUcarTdExcludeKeys = () => getUcarTdExcludeCols().map(v => v.id)
