export type JP_TABLE_NAME = '古物台帳DB' | '在庫情報DB' | 'AI査定' | 'QRプロセス'
export type EN_TABLE_NAME = 'OldCars_Base' | 'ZAIKO_Base' | 'AI_satei' | 'QR_Prosess'
export type DATASET_ID = 'OrdersDB' | 'Ucar_QR'

export const UCAR_TABLES: {
  jpName: JP_TABLE_NAME
  enName: EN_TABLE_NAME
  datasetId: DATASET_ID
  whereStr?: string
  uniqueKeyToUpsert: {keyName: string; data: string[]; orderBy?: string}
  fields: {en: string; jp: string}[]
}[] = [
  {
    jpName: '古物台帳DB',
    enName: 'OldCars_Base',
    datasetId: 'OrdersDB',
    uniqueKeyToUpsert: {
      keyName: '',
      data: ['NO_SIRETOSE', 'NO_FRAME'],
      orderBy: 'DD_SIIRE',
    },
    whereStr: `LENGTH("APPINDEX") <= 25`,
    fields: [
      {en: 'APPINDEX', jp: 'APPINDEX'},
      {en: 'CD_21SYAMEI', jp: 'AI21車名コード'},
      {en: 'MJ_SYAMEI', jp: '車名'},
      {en: 'CD_HANSTAFF', jp: '販売スタッフコード'},
      {en: 'CD_HANTENPO', jp: '販売店舗'},
      {en: 'NO_SIRETYUM', jp: '仕入注文NO'},
      {en: 'MJ_SIRENORI', jp: '仕入時陸支'},
      {en: 'KB_SIRETOSY', jp: '仕入時車種区分'},
      {en: 'CD_SIRETOGY', jp: '仕入時業態区分'},
      {en: 'NO_SIRETOSE', jp: '仕入時整理番号'},
      {en: 'NO_HANJTRIK', jp: '販売時陸支'},
      {en: 'KB_HANTOSY', jp: '販売時車種区分'},
      {en: 'CD_HANTOGY', jp: '販売時業態区分'},
      {en: 'NO_HANTOSE', jp: '販売時整理番号'},
      {en: 'CD_SITASTAF', jp: '下取りスタッフ'},
      {en: 'DD_SIIRE', jp: '仕入日'},
      {en: 'DD_SIREBD', jp: '仕入先_生年月日'},
      {en: 'SU_SYODOTOR', jp: '初度登録日'},
      {en: 'NO_FRAME', jp: 'フレームNO'},
      {en: 'KI_SIIREKA', jp: '仕入れ価格'},
      {en: 'KI_HANKAKA', jp: '販売価格'},
      {en: 'KB_SIIRE', jp: '仕入区分'},
      {en: 'KB_SIHARAI', jp: '支払区分'},
      {en: 'KB_URIAGE', jp: '売上区分'},
      {en: 'NO_CYUMON', jp: '注文NO'},
      {en: 'NO_CYUMONED', jp: '注文NO枝番'},
      {en: 'NO_SYARYOU', jp: '車両NO'},
      {en: 'NO_SYADAIBA', jp: '車台番号'},
      {en: 'DT_SAISINUP', jp: '最終更新日'},
      {en: 'MJ_KATASIKI', jp: '型式'},
      {en: 'NU_SOUKOUKM', jp: '走行キロ'},
      {en: 'CD_SIRETENP', jp: '仕入店舗'},
      {en: 'KJ_SIRESAKI', jp: '仕入先名'},
      {en: 'KB_UC1JTORO', jp: '中古車一時登録区分'},
      {en: 'DD_URIAGE', jp: '売上区分'},
      {en: 'DD_1JTOROKU', jp: '一時登録日'},
      {en: 'DD_2JTOROKU', jp: '二次登録日'},
      {en: 'DD_SYKNMANR', jp: '車検満了日'},
      {en: 'DD_SITASYUK', jp: '下取り受取日'},
      {en: 'DD_NOSYA', jp: '納車日'},
      {en: 'MJ_SITADOTE', jp: '下取店舗'},
    ],
  },
  {
    jpName: '在庫情報DB',
    enName: 'ZAIKO_Base',
    datasetId: 'OrdersDB',
    whereStr: `LENGTH("APPINDEX") <= 25`,
    uniqueKeyToUpsert: {
      keyName: '',
      data: ['NO_SIRETOSE', 'NO_FRAME'],
      orderBy: '',
    },
    fields: [
      {en: 'APPINDEX', jp: 'ユニークキー'},
      {en: 'NO_SYARYOU', jp: '車両ＮＯ'},
      {en: 'KB_SIIRE', jp: '仕入区分'},
      {en: 'DD_KEIRIKEI', jp: '経理計上日'},
      {en: 'NO_SIRETYUM', jp: '仕入注文ＮＯ'},
      {en: 'MJ_SIRENORI', jp: '仕入時登録ＮＯ陸支コード'},
      {en: 'KB_SIRETOSY', jp: '仕入時登録ＮＯ車種区分'},
      {en: 'CD_SIRETOGY', jp: '仕入時登録ＮＯ業態コード'},
      {en: 'NO_SIRETOSE', jp: '仕入時登録ＮＯ整理番号'},
      {en: 'MJ_SIRESAKI', jp: '仕入先名'},
      {en: 'CD_SITADOTE', jp: '下取店舗コード'},
      {en: 'CD_SITASTAF', jp: '下取スタッフコード'},
      {en: 'CD_SIRETENP', jp: '仕入店舗コード'},
      {en: 'MJ_FURUSYAM', jp: 'フル車名'},
      {en: 'NO_KATASIKI', jp: '型式ＮＯ'},
      {en: 'NO_FRAME', jp: 'フレームＮＯ'},
      {en: 'CD_TENJTENP', jp: '展示予定店舗コード'},
      {en: 'KI_HNBSIJIK', jp: '販売指示価格'},
      {en: 'KI_TENTOHYJ', jp: '店頭表示価格'},
      {en: 'CD_ZAIKSYYS', jp: '在庫照会用色コード'},
      {en: 'KB_SYASYHAN', jp: '車種判定区分'},
      {en: 'NO_SYADAIBA', jp: '車台番号'},
      {en: 'KI_SIIREKA', jp: '仕入価格'},
      {en: 'KN_KEI', jp: '軽区分'},
      {en: 'MJ_ZAIKOST', jp: '在庫ステータス'},
      {en: 'CD_ZAIKOTEN', jp: '在庫店舗コード'},
      {en: 'NO_CYUMON', jp: '注文ＮＯ'},
      {en: 'KB_URIAGE', jp: '売上区分'},
      {en: 'CD_HANSTAFF', jp: '販売スタッフコード'},
      {en: 'MJ_21SYASYS', jp: 'ａｉ２１車名コード車種市場'},
      {en: 'MJ_SIJYOKBM', jp: '車種市場区分'},
      {en: 'DT_SAISINUP', jp: '最新更新日時'},
      {en: 'APPINDEX_FKEY', jp: '連携用キー'},
    ],
  },

  {
    jpName: `AI査定`,
    enName: `AI_satei`,
    datasetId: 'Ucar_QR',
    uniqueKeyToUpsert: {keyName: 'Assessment_ID', data: ['Assessment_ID']},
    fields: [
      // {en: 'User_ID', jp: 'ユーザーID'},
      {en: 'Assessment_ID', jp: '査定ID'},
      {en: 'Barracks', jp: '車台番号'},
      {en: 'number', jp: 'ナンバー'},
      {en: 'Model_name', jp: '車種名'},
      {en: 'brand_name', jp: 'ブランド名'},
      {en: 'Common_name_model', jp: '通称型式'},
      {en: 'Model_year', jp: '年式'},
      {en: 'Scheduled_arrival_date', jp: '入庫予定日'},
      {en: 'Number_Place_name', jp: 'ナンバー_地名'},
      {en: 'Number_classification_number', jp: 'ナンバー_分類番号'},
      {en: 'Number_Hiragana', jp: 'ナンバー_ひらがな'},
      {en: 'Vehicle_length', jp: '車寸（長さ）'},
      {en: 'Vehicle_width', jp: '車寸（幅）'},
      {en: 'Vehicle_height', jp: '車寸（高さ）'},
      // {en: 'brand_name', jp: 'ブランド名'},
      // {en: 'Common_name_model', jp: '通称型式'},
      // {en: 'Latest_assessment_date', jp: '最新査定日付'},
      // {en: 'Latest_assessment_time', jp: '最新査定時刻'},
      // {en: 'Initial_assessment_date', jp: '初回査定日付'},
      // {en: 'Initial_assessment_time', jp: '初回査定時刻'},
      // {en: 'QR_reading_or_not', jp: 'QR読取有無'},
      // {en: 'Priority_number', jp: '優先度番号'},
      // {en: 'Priority_use', jp: '優先度使用'},
      // {en: 'Approval_state', jp: '承認状態'},
      // {en: 'Approved_user_name_1', jp: '承認ユーザ名(1次)'},
      // {en: 'Approval_price_1', jp: '承認価格(1次)'},
      // {en: 'Approval_date_1', jp: '承認日付(1次)'},
      // {en: 'Time_to_approve_1', jp: '承認までの時間(1次)'},
      // {en: 'Approval_user_name_2', jp: '承認ユーザ名(2次)'},
      // {en: 'Approval_price_2', jp: '承認価格(2次)'},
      // {en: 'Approval_date_2', jp: '承認日付(2次)'},
      // {en: 'Time_to_approve_2', jp: '承認までの時間(2次)'},
      // {en: 'Approval_memo_column', jp: '承認者メモ欄'},
      // {en: 'Pending_comment', jp: '保留コメント'},
      // {en: 'Number_of_people_holding', jp: '保留回数'},
      // {en: 'Standard_price', jp: '基準価格'},
      // {en: 'Display_price_at_the_time_of_assessment_registration', jp: '査定登録時表示価格'},
      // {en: 'Adjustment_adjustment_price', jp: '加減算調整価格'},
      // {en: 'Latest_assessment_price', jp: '最新査定価格'},
      // {en: 'Malary_profit_correction_after_price', jp: '粗利補正後価格'},
      // {en: 'Model_specification_No', jp: '型式指定No'},
      // {en: 'Classic_NO', jp: '類別No'},
      // {en: 'Country_name', jp: '国名'},

      // {en: 'Model_name', jp: '車種名'},
      // {en: 'Model_cycle_name', jp: 'モデルサイクル名'},
      // {en: 'First_registration_year_1', jp: '初度登録年(西暦)'},
      // {en: 'First_registration_year_2', jp: '初度登録年(和暦)'},
      // {en: 'Initial_registration_date', jp: '初度登録年月'},
      // {en: 'Model', jp: '型式(エンジン記号付)'},

      // {en: 'Certified_type', jp: '認定型式'},
      // {en: 'Grade_name', jp: 'グレード名'},
      // {en: 'Mission_name', jp: 'ミッション名'},
      // {en: 'Capacity', jp: '定員'},
      // {en: 'Door_name', jp: 'ドア名'},
      // {en: 'Displacement', jp: '排気量'},
      // {en: 'Driving', jp: '駆動'},
      // {en: 'Vehicle_length', jp: '車寸（長さ）'},
      // {en: 'Vehicle_width', jp: '車寸（幅）'},
      // {en: 'Vehicle_height', jp: '車寸（高さ）'},
      // {en: 'handle', jp: 'ハンドル'},
      // {en: 'Category_domestic_or_import', jp: '区分(国産/輸入)'},
      // {en: 'Import_category', jp: '輸入区分'},
      // {en: 'Number_Place_name', jp: 'ナンバー_地名'},
      // {en: 'Number_classification_number', jp: 'ナンバー_分類番号'},
      // {en: 'Number_Hiragana', jp: 'ナンバー_ひらがな'},

      // {en: 'Date_of_registration_date_issued', jp: '登録年月日/交付年月日'},
      // {en: 'Vehicle_inspection_year', jp: '車検(年)'},
      // {en: 'Vehicle_inspection_month', jp: '車検(月)'},
      // {en: 'Vehicle_inspection_date', jp: '車検満了日'},
      // {en: 'Owner_Name', jp: '所有者_氏名又は名称'},
      // {en: 'Owner_Address', jp: '所有者_住所'},
      // {en: 'User_Name', jp: '使用者_氏名又は名称'},
      // {en: 'User_Address', jp: '使用者_住所'},
      // {en: 'Serial_NO', jp: 'シリアルNo'},
      // {en: 'Recycling_deposit_flag', jp: 'リサイクル預託金フラグ'},
      // {en: 'Shredder_dust_fee', jp: 'シュレッダーダスト料金'},
      // {en: 'Airbag_fee_fee', jp: 'エアバック類料金'},
      // {en: 'Freon_fee', jp: 'フロン類料金'},
      // {en: 'Information_management_fee', jp: '情報管理料金'},
      // {en: 'Total_recycling_deposits', jp: 'リサイクル預託金合計'},
      // {en: 'Car_history', jp: '車歴'},
      // {en: 'Body_color', jp: '車体色'},
      // {en: 'Color_based_name', jp: '色系統名称'},
      // {en: 'Color_code', jp: 'カラーコード'},
      // {en: 'Catalog_color', jp: 'カタログカラー'},
      // {en: 'Color_change', jp: '色替え'},
      // {en: 'Interior_color', jp: '内装色'},
      // {en: 'Interior_equipment_consideration', jp: '内装備考'},
      // {en: 'Unknown_mileage_flag', jp: '走行距離不明フラグ'},
      // {en: 'Mileage', jp: '走行距離'},
      // {en: 'Mileage_unit', jp: '走行距離単位'},
      // {en: 'Meter_exchange_distance', jp: 'メーター交換距離'},
      // {en: 'Meter_exchange_distance_unit', jp: 'メーター交換距離単位'},
      // {en: 'Meter_tampering', jp: 'メーター改竄'},
      // {en: 'sunroof', jp: 'サンルーフ'},
      // {en: 'Leather_seat', jp: 'レザーシート'},
      // {en: 'Navi_yes_or_no', jp: 'ナビ(有/無)'},
      // {en: 'Display_type', jp: 'ディスプレイタイプ'},
      // {en: 'Navigation', jp: 'ナビメディア'},
      // {en: 'Navi_remarks', jp: 'ナビ備考'},
      // {en: 'Interior_state', jp: '内装状態'},
      // {en: 'institution', jp: '機関'},
      // {en: 'Electrical_equipment', jp: '電装'},
      // {en: 'fuel', jp: '燃料'},
      // {en: 'Next_purchase_car', jp: '次期購入車'},
      // {en: 'Scheduled_arrival_date', jp: '入庫予定日'},
      // {en: 'Wound_information', jp: '傷情報'},
      // {en: 'Whether_or_not_the_front_tire_size_is_changed', jp: 'フロントタイヤサイズ変更有無'},
      // {en: 'Front_tire_size_before_change', jp: '変更前フロントタイヤサイズ'},
      // {en: 'Changed_front_tire_size', jp: '変更後フロントタイヤサイズ'},
      // {en: 'Rear_tire_size_change', jp: 'リアタイヤサイズ変更有無'},
      // {en: 'Before_the_rear_tire_size', jp: '変更前リアタイヤサイズ'},
      // {en: 'Rear_tire_size_after_change', jp: '変更後リアタイヤサイズ'},
      // {en: 'Right_front_tire', jp: '右前タイヤ'},
      // {en: 'Left_front_tire', jp: '左前タイヤ'},
      // {en: 'Right_and_right_tires', jp: '右後タイヤ'},
      // {en: 'Left_tire', jp: '左後タイヤ'},
      // {en: 'Preliminary_tires', jp: '予備タイヤ有無'},
      // {en: 'Spare_tire', jp: '予備タイヤ'},
      // {en: 'Wheel_scratch___right_front', jp: 'ホイールキズ_右前'},
      // {en: 'Wheel_scratch___left_front', jp: 'ホイールキズ_左前'},
      // {en: 'Wheel_scratch___Right_after', jp: 'ホイールキズ_右後'},
      // {en: 'Wheel_scratch___left_rear', jp: 'ホイールキズ_左後'},
      // {en: 'Truck_right_tire_with_right_tires', jp: 'トラック右タイヤ有無'},
      // {en: 'Truck_right_tire_condition', jp: 'トラック右タイヤ状態'},
      // {en: 'Truck_left_tire_with_left_tires', jp: 'トラック左タイヤ有無'},
      // {en: 'Truck_left_tire_condition', jp: 'トラック左タイヤ状態'},
      // {en: 'Preliminary_truck_tires', jp: '予備トラックタイヤ有無'},
      // {en: 'Preliminary_truck_tire_condition', jp: '予備トラックタイヤ状態'},
      // {en: 'Truck_right_tire_wheel_condition', jp: 'トラック右タイヤホイール状態'},
      // {en: 'Truck_left_tire_wheel_condition', jp: 'トラック左タイヤホイール状態'},
      // {en: 'Preliminary_truck_tire_wheel_condition', jp: '予備トラックタイヤホイール状態'},
      // {en: 'Repair_information', jp: '修復情報'},
      // {en: 'Repair_status_preparation', jp: '修復状態備考'},
      // {en: 'Remarks_for_the_current_accident', jp: '事故現状備考'},
      // {en: 'Evaluation_points', jp: '評価点'},
      // {en: 'Exterior_evaluation_point', jp: '外装評価点'},
      // {en: 'Interior_evaluation_point', jp: '内装評価点'},
      // {en: 'Assessment_evaluation_point', jp: '査定者評価点'},
      // {en: 'Assessment_exterior_evaluation', jp: '査定者外装評価'},
      // {en: 'Air_conditioner', jp: 'エアコン'},
      // {en: 'sales_point', jp: 'セールスポイント'},
      // {en: 'Restoration_state', jp: '修復状態'},
      // {en: 'Other_information', jp: 'その他情報'},
      // {en: 'Store_name', jp: '店舗名'},
      // {en: 'Assessment_person_in_charge', jp: '査定担当者'},
      // {en: 'Warehouse_status', jp: '入庫ステータス'},
      // {en: 'Home_phone_number', jp: '自宅電話番号'},
      // {en: 'Home_postal_code', jp: '自宅郵便番号'},
      // {en: 'Home_Address', jp: '自宅住所'},
      // {en: 'Order_card_No', jp: '注文書ＮＯ'},
      // {en: 'SG_client_store_name', jp: 'SGクライアント店舗名'},
      // {en: 'Question_1', jp: '設問1'},
      // {en: 'Question_type_1', jp: '設問タイプ1'},
      // {en: 'Answer_1', jp: '回答1'},
      // {en: 'Question_2', jp: '設問2'},
      // {en: 'Question_type_2', jp: '設問タイプ2'},
      // {en: 'Answer_2', jp: '回答2'},
      // {en: 'Question_3', jp: '設問3'},
      // {en: 'Question_type_3', jp: '設問タイプ3'},
      // {en: 'Answer_3', jp: '回答3'},
      // {en: 'Question_4', jp: '設問4'},
      // {en: 'Question_type_4', jp: '設問タイプ4'},
      // {en: 'Answer_4', jp: '回答4'},
      // {en: 'Question_5', jp: '設問5'},
      // {en: 'Question_type_5', jp: '設問タイプ5'},
      // {en: 'Answer_5', jp: '回答5'},
      // {en: 'Question_6', jp: '設問6'},
      // {en: 'Question_type_6', jp: '設問タイプ6'},
      // {en: 'Answer_6', jp: '回答6'},
      // {en: 'Question_7', jp: '設問7'},
      // {en: 'Question_type_7', jp: '設問タイプ7'},
      // {en: 'Answer_7', jp: '回答7'},
      // {en: 'Question_8', jp: '設問8'},
      // {en: 'Question_type_8', jp: '設問タイプ8'},
      // {en: 'Answer_8', jp: '回答8'},
      // {en: 'Question_9', jp: '設問9'},
      // {en: 'Question_type_9', jp: '設問タイプ9'},
      // {en: 'Answer_9', jp: '回答9'},
      // {en: 'Question_10', jp: '設問10'},
      // {en: 'Question_type_10', jp: '設問タイプ10'},
      // {en: 'Answer_10', jp: '回答10'},
      // {en: 'Customer_name', jp: 'お客様氏名'},
      // {en: 'Unlocking_ownership', jp: '所有権解除'},
      // {en: 'mail_address', jp: 'メールアドレス'},
      // {en: 'Model_year', jp: 'モデル年式'},
      // {en: 'engine', jp: 'エンジン'},
      // {en: 'turbo', jp: 'ターボ'},
      // {en: 'shape', jp: '形状'},
      // {en: 'Deposit_date', jp: '預託日'},
      // {en: 'Liability_from', jp: '自賠責From'},
      // {en: 'Liability_to', jp: '自賠責To'},
      // {en: 'Motor_model', jp: '原動機の型式'},
      // {en: 'Meter_exchange', jp: 'メーター交換'},
      // {en: 'Email_reflection_comment', jp: 'メール反映コメント'},
      // {en: 'Assessment_reflection_comment', jp: '査定反映コメント'},
      // {en: 'Warehouse_status_date', jp: '入庫ステータス日付'},
      // {en: 'comment', jp: 'コメント'},
      // {en: 'Wholesale_price', jp: '卸価格'},
      // {en: 'retail_price', jp: '小売価格'},
      // {en: 'Assessment_additional_price_price', jp: '査定者加減算価格'},
      // {en: 'Reason_for_adjusting', jp: '加減算理由'},
      // {en: 'sales_representative', jp: '営業担当者'},
      // {en: 'Desired_assessment_price', jp: '希望査定価格'},
      // {en: 'Reason_for_the_desired_assessment_price', jp: '希望査定価格理由'},
      // {en: 'PDF_reading_or_not', jp: 'PDF読取有無'},
      // {en: 'Tire_punk_repair_kit', jp: 'タイヤパンク修理キット'},
      // {en: 'Taxable_unearned_auto_tax', jp: '自動車税未経過相当額の課税対象'},
      // {en: 'Auto_tax_unearned', jp: '自動車税未経過相当額'},
      // {en: 'consumption_tax', jp: '消費税'},
      // {en: 'total', jp: '合計'},
    ],
  },
  {
    jpName: `QRプロセス`,
    datasetId: `Ucar_QR`,
    enName: `QR_Prosess`,
    uniqueKeyToUpsert: {keyName: 'sateiId', data: ['sateiId']},
    fields: [
      {en: 'sateiId', jp: '査定ID'},
      {en: 'Sorting_results', jp: '仕分結果'},
      {en: 'datetime_0', jp: 'タイムスタンプ'},
      {en: 'email_0', jp: 'メールアドレス'},
      {en: 'store_0', jp: '引取先拠点'},
      {en: 'runnable_0', jp: '自力走行可'},
      {en: 'remarks_0', jp: '店舗特記事項'},
      {en: 'shitadoriKubun_0', jp: '下取り区分'},
      {en: 'orderNumber_0', jp: '注文No'},
      {en: 'datetime_1', jp: '1 拠点入庫'},
      {en: 'datetime_2', jp: '2引取依頼'},
      {en: 'datetime_3', jp: '3.受入待'},
      {en: 'datetime_4', jp: '4.受入終了'},
      {en: 'datetime_6', jp: '6.検収終了'},
      {en: 'datetime_7', jp: '7.加修開始'},
      {en: 'datetime_8', jp: '8.加修終了'},
      {en: 'datetime_9', jp: '9.まるクリ終了'},
      {en: 'datetime_11', jp: '11.検査終了'},
      {en: 'datetime_12', jp: '12.撮影終了'},
      {en: 'datetime_13', jp: '13.GAZOO'},
      {en: 'datetime_14', jp: '14.商品車受取'},
      {en: 'max_update', jp: '最大更新日'},
    ],
  },
]

export const allFields = UCAR_TABLES.flatMap(table => table.fields)
