// export const aiSateiCols: upassColumn[] = [
//   {
//     jp: '査定ID',
//     en: 'Assessment_ID',
//     sampleData: null,
//     category: 'ID',
//   },
//   {
//     jp: 'QR読取有無',
//     en: 'QR_reading_or_not',
//     sampleData: null,
//     category: 'ASSESSMENT_IMPLEMETATION',
//   },
//   {
//     jp: '承認状態',
//     en: 'Approval_state',
//     sampleData: null,
//     category: 'ASSESSMENT_IMPLEMETATION',
//   },
//   {
//     jp: '最新査定価格',
//     en: 'Latest_assessment_price',
//     sampleData: null,
//     category: 'ASSESSMENT_RESULT',
//   },
//   {
//     jp: '粗利補正後価格',
//     en: 'Malary_profit_correction_after_price',
//     sampleData: null,
//     category: 'ASSESSMENT_RESULT',
//   },
//   {
//     jp: '型式指定No',
//     en: 'Model_specification_No',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: '類別No',
//     en: 'Classic_NO',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: '国名',
//     en: 'Country_name',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: 'ブランド名',
//     en: 'brand_name',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: '車種名',
//     en: 'Model_name',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: 'モデルサイクル名',
//     en: 'Model_cycle_name',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: '初度登録年(西暦)',
//     en: 'First_registration_year_1',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: '初度登録年(和暦)',
//     en: 'First_registration_year_2',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: '初度登録年月',
//     en: 'Initial_registration_date',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: '型式(エンジン記号付)',
//     en: 'Model',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: '通称型式',
//     en: 'Common_name_model',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: '認定型式',
//     en: 'Certified_type',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: 'グレード名',
//     en: 'Grade_name',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: 'ミッション名',
//     en: 'Mission_name',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: '定員',
//     en: 'Capacity',
//     sampleData: null,
//     category: 'SIZE',
//   },
//   {
//     jp: 'ドア名',
//     en: 'Door_name',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: '排気量',
//     en: 'Displacement',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: '駆動',
//     en: 'Driving',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: 'ハンドル',
//     en: 'handle',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: '区分(国産/輸入)',
//     en: 'Category_domestic_or_import',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: '輸入区分',
//     en: 'Import_category',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: 'ナンバー_地名',
//     en: 'Number_Place_name',
//     sampleData: null,
//     category: 'PLATE',
//   },
//   {
//     jp: 'ナンバー_分類番号',
//     en: 'Number_classification_number',
//     sampleData: null,
//     category: 'PLATE',
//   },
//   {
//     jp: 'ナンバー_ひらがな',
//     en: 'Number_Hiragana',
//     sampleData: null,
//     category: 'PLATE',
//   },
//   {
//     jp: 'ナンバー',
//     en: 'number',
//     sampleData: null,
//     category: 'PLATE',
//   },
//   {
//     jp: '車台番号',
//     en: 'Barracks',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: '登録年月日/交付年月日',
//     en: 'Date_of_registration_date_issued',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: '車検(年)',
//     en: 'Vehicle_inspection_year',
//     sampleData: null,
//     category: 'JIBAN',
//   },
//   {
//     jp: '車検(月)',
//     en: 'Vehicle_inspection_month',
//     sampleData: null,
//     category: 'JIBAN',
//   },
//   {
//     jp: '車検満了日',
//     en: 'Vehicle_inspection_date',
//     sampleData: null,
//     category: 'JIBAN',
//   },
//   {
//     jp: '所有者_氏名又は名称',
//     en: 'Owner_Name',
//     sampleData: null,
//     category: 'CUSTOMER',
//   },
//   {
//     jp: '使用者_氏名又は名称',
//     en: 'User_Name',
//     sampleData: null,
//     category: 'CUSTOMER',
//   },
//   {
//     jp: 'シリアルNo',
//     en: 'Serial_NO',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: 'リサイクル預託金フラグ',
//     en: 'Recycling_deposit_flag',
//     sampleData: null,
//     category: 'RECYCLING',
//   },
//   {
//     jp: 'シュレッダーダスト料金',
//     en: 'Shredder_dust_fee',
//     sampleData: null,
//     category: 'RECYCLING',
//   },
//   {
//     jp: 'エアバック類料金',
//     en: 'Airbag_fee_fee',
//     sampleData: null,
//     category: 'RECYCLING',
//   },
//   {
//     jp: 'フロン類料金',
//     en: 'Freon_fee',
//     sampleData: null,
//     category: 'RECYCLING',
//   },
//   {
//     jp: '情報管理料金',
//     en: 'Information_management_fee',
//     sampleData: null,
//     category: 'RECYCLING',
//   },
//   {
//     jp: 'リサイクル預託金合計',
//     en: 'Total_recycling_deposits',
//     sampleData: null,
//     category: 'RECYCLING',
//   },
//   {
//     jp: '車歴',
//     en: 'Car_history',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: '車体色',
//     en: 'Body_color',
//     sampleData: null,
//     category: 'BODY_INFO',
//   },
//   {
//     jp: '色系統名称',
//     en: 'Color_based_name',
//     sampleData: null,
//     category: 'BODY_INFO',
//   },
//   {
//     jp: 'カラーコード',
//     en: 'Color_code',
//     sampleData: null,
//     category: 'BODY_INFO',
//   },
//   {
//     jp: '内装色',
//     en: 'Interior_color',
//     sampleData: null,
//     category: 'BODY_INFO',
//   },
//   {
//     jp: '走行距離',
//     en: 'Mileage',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: '走行距離単位',
//     en: 'Mileage_unit',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
//   {
//     jp: 'サンルーフ',
//     en: 'sunroof',
//     sampleData: null,
//     category: 'EQUIPMENT',
//   },
//   {
//     jp: 'レザーシート',
//     en: 'Leather_seat',
//     sampleData: null,
//     category: 'EQUIPMENT',
//   },
//   {
//     jp: 'ナビ(有/無)',
//     en: 'Navi_yes_or_no',
//     sampleData: null,
//     category: 'ADVANCED_EQUIPMENT',
//   },
//   {
//     jp: 'ディスプレイタイプ',
//     en: 'Display_type',
//     sampleData: null,
//     category: 'ADVANCED_EQUIPMENT',
//   },
//   {
//     jp: 'ナビメディア',
//     en: 'Navigation',
//     sampleData: null,
//     category: 'ADVANCED_EQUIPMENT',
//   },
//   {
//     jp: 'ナビ備考',
//     en: 'Navi_remarks',
//     sampleData: null,
//     category: 'ADVANCED_EQUIPMENT',
//   },
//   {
//     jp: '内装状態',
//     en: 'Interior_state',
//     sampleData: null,
//     category: 'BODY_INFO',
//   },
//   {
//     jp: '機関',
//     en: 'institution',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: '電装',
//     en: 'Electrical_equipment',
//     sampleData: null,
//     category: 'EQUIPMENT',
//   },
//   {
//     jp: '燃料',
//     en: 'fuel',
//     sampleData: null,
//     category: 'GRADE',
//   },
//   {
//     jp: '評価点',
//     en: 'Evaluation_points',
//     sampleData: null,
//     category: 'ASSESSMENT_RESULT',
//   },
//   {
//     jp: '店舗名',
//     en: 'Store_name',
//     sampleData: null,
//     category: 'ASSESSMENT_IMPLEMETATION',
//   },
//   {
//     jp: '査定担当者',
//     en: 'Assessment_person_in_charge',
//     sampleData: null,
//     category: 'ASSESSMENT_IMPLEMETATION',
//   },
//   {
//     jp: 'モデル年式',
//     en: 'Model_year',
//     sampleData: null,
//     category: 'CAR_INFO',
//   },
// ]
