export const upassCols: upassColumn[] = [
  {
    jp: '値付販売店名',
    en: 'dealerName',
    sampleData: 'P岡山',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '値付販売店コード',
    en: 'dealerCode',
    sampleData: '16301',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '査定モード',
    en: 'assessmentMode',
    sampleData: '店舗査定',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '査定モード2',
    en: 'assessmentMode2',
    sampleData: null,
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '状態',
    en: 'status',
    sampleData: '回答済',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '値付種類',
    en: 'valuationType',
    sampleData: '集中値付',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '値付番号',
    en: 'valuationNumber',
    sampleData: '163012408000008',
    category: 'ASSESSMENT_IMPLEMETATION',
  },

  //ID
  {
    jp: '査定番号',
    en: 'sateiID',
    sampleData: '163012408000017',
    category: 'ID',
    showIn: {
      qrCreate: {label: '査定番号'},
      // ucarMainTable: {label: '査定番号'},
    },
  },
  {
    jp: 'PAL査定番号',
    en: 'palAssessmentNumber',
    sampleData: null,
    category: 'ID',
  },

  //プレート
  {
    jp: '店舗査定_陸事名',
    en: 'landAffairsName',
    sampleData: '倉敷',
    category: 'PLATE',
  },
  {
    jp: '店舗査定_登録番号_分類番号_',
    en: 'registrationClassNumber',
    sampleData: '330',
    category: 'PLATE',
  },
  {
    jp: '店舗査定_登録番号_かな_',
    en: 'registrationKana',
    sampleData: 'ひ',
    category: 'PLATE',
  },
  {
    jp: '店舗査定_登録番号_一連指定番号_',
    en: 'registrationSerialNumber',
    sampleData: '1625',
    category: 'PLATE',
  },
  {
    jp: '店舗査定_登録年月日_交付年月日',
    en: 'registrationDate',
    type: 'date',
    sampleData: '2022/10/13',
    category: 'PLATE',
  },

  //年式・車台番号・車両情報
  {
    jp: '店舗査定_初度登録年月',
    en: 'firstRegistrationDate',
    sampleData: '202210',
    category: 'CAR_INFO',
  },
  {
    jp: '店舗査定_年式_落ち年数_',
    en: 'modelYear',
    sampleData: '3',
    category: 'CAR_INFO',
  },
  {
    jp: '店舗査定_年式区分',
    en: 'modelYearType',
    sampleData: 'B',
    category: 'CAR_INFO',
  },

  {
    jp: '店舗査定_車台番号',
    en: 'chassisNumber',
    sampleData: 'AZSH35-4002743',
    category: 'CAR_INFO',
    showIn: {
      ucarMainTable: {label: '車体番号'},
    },
  },
  {
    jp: '店舗査定_フレームNo',
    en: 'frameNumber',
    sampleData: '4002743',
    category: 'CAR_INFO',
    showIn: {
      qrCreate: {label: 'フレーム番号'},
    },
  },
  {
    jp: '店舗査定_ブランド名称',
    en: 'brandName',
    sampleData: 'ﾄﾖﾀ',
    category: 'CAR_INFO',
    showIn: {
      qrCreate: {label: 'ブランド名称'},
      ucarMainTable: {label: 'ブランド名称'},
    },
  },
  {
    jp: '店舗査定_車種名称',
    en: 'modelName',
    sampleData: 'ｸﾗｳﾝ_ｸﾛｽｵｰﾊﾞｰ_',
    category: 'CAR_INFO',
  },
  {
    jp: '店舗査定_ai21車名コード',
    en: 'ai21ModelCode',
    sampleData: 'A14F27',
    category: 'CAR_INFO',
  },

  //型式・グレードなど
  {
    jp: '店舗査定_グレード',
    en: 'grade',
    sampleData: '2.5 CROSSOVER G"Advanced･Leather Package"',
    category: 'GRADE',
    showIn: {
      qrCreate: {label: 'グレード'},
      ucarMainTable: {label: 'グレード'},
    },
  },
  {
    jp: '店舗査定_型式',
    en: 'type',
    sampleData: '6AA-AZSH35',
    category: 'GRADE',
    showIn: {
      qrCreate: {label: '型式'},
      ucarMainTable: {label: '型式'},
    },
  },
  {
    jp: '店舗査定_通称型式',
    en: 'commonType',
    sampleData: 'AZSH35-AEXMB_I_',
    category: 'GRADE',
    showIn: {
      qrCreate: {label: '通称型式'},
    },
  },
  {
    jp: '店舗査定_原動機型式',
    en: 'engineType',
    sampleData: 'A25A-3NM-4NM',
    category: 'GRADE',
  },
  {
    jp: '店舗査定_車歴',
    en: 'vehicleHistory',
    sampleData: '自家用',
    category: 'GRADE',
  },

  //定員、重量、サイズなど
  {
    jp: '店舗査定_定員_最小_',
    en: 'capacityMin',
    sampleData: '5',
    category: 'SIZE',
  },
  {
    jp: '店舗査定_定員_最大_',
    en: 'capacityMax',
    sampleData: '0',
    category: 'SIZE',
  },
  {
    jp: '店舗査定_最大積載量',
    en: 'maxLoad',
    sampleData: '0',
    category: 'SIZE',
  },
  {
    jp: '店舗査定_重量',
    en: 'weight',
    sampleData: '1790',
    category: 'SIZE',
  },
  {
    jp: '店舗査定_総重量',
    en: 'grossWeight',
    sampleData: '2065',
    category: 'SIZE',
  },
  {
    jp: '店舗査定_全長',
    en: 'length',
    sampleData: '493',
    category: 'SIZE',
  },
  {
    jp: '店舗査定_全幅',
    en: 'width',
    sampleData: '184',
    category: 'SIZE',
  },
  {
    jp: '店舗査定_全高',
    en: 'height',
    sampleData: '154',
    category: 'SIZE',
  },
  {
    jp: '店舗査定_排気量',
    en: 'displacement',
    sampleData: '2500',
    category: 'SIZE',
  },
  {
    jp: '店舗査定_燃料名称',
    en: 'fuelName',
    sampleData: 'ﾊｲﾌﾞﾘｯﾄﾞ',
    category: 'SIZE',
  },
  {
    jp: '店舗査定_型式指定番号',
    en: 'typeDesignationNumber',
    sampleData: '20467',
    category: 'SIZE',
  },
  {
    jp: '店舗査定_類別区分番号',
    en: 'categoryNumber',
    sampleData: '40',
    category: 'SIZE',
  },

  /////所有者・使用者・aiお客様データ
  {
    jp: '店舗査定_所有者名',
    en: 'ownerName',
    sampleData: '岡山トヨペット株式会社',
    category: 'CUSTOMER',
  },
  {
    jp: '店舗査定_使用者名',
    en: 'userName',
    sampleData: '實石 賢二',
    category: 'CUSTOMER',
  },
  {
    jp: '店舗査定_使用所有同一フラグ',
    en: 'useOwnershipSameFlag',
    sampleData: null,
    category: 'CUSTOMER',
  },
  {
    jp: '店舗査定_ai21お客様コード',
    en: 'ai21CustomerCode',
    sampleData: '221000152',
    category: 'CUSTOMER',
  },
  {
    jp: '店舗査定_お客様名',
    en: 'customerName',
    sampleData: '實石 賢二',
    category: 'CUSTOMER',
  },
  {
    jp: '店舗査定_お客様カナ姓',
    en: 'customerKanaSurname',
    sampleData: 'ミイシ',
    category: 'CUSTOMER',
  },
  {
    jp: '店舗査定_お客様カナ名',
    en: 'customerKanaName',
    sampleData: 'ケンジ',
    category: 'CUSTOMER',
  },

  {
    jp: '店舗査定_車検満了年月日',
    en: 'inspectionExpiryDate',
    type: 'date',
    sampleData: '2025/10/12',
    category: 'CUSTOMER',
  },
  {
    jp: '店舗査定_走行距離計表示値_車検証_',
    en: 'odometerDisplayValue',
    sampleData: null,
    category: 'CUSTOMER',
  },

  //付属品
  {
    jp: '店舗査定_新車保証書有無',
    en: 'newCarWarranty',
    sampleData: 'あり',
    category: 'DOCUMENT',
  },
  {
    jp: '店舗査定_整備手帳有無',
    en: 'maintenanceManual',
    sampleData: 'あり',
    category: 'DOCUMENT',
  },
  {
    jp: '店舗査定_取扱説明書有無',
    en: 'instructionManual',
    sampleData: 'あり',
    category: 'DOCUMENT',
  },
  {
    jp: '店舗査定_定期点検記録簿内容',
    en: 'periodicInspectionRecord',
    sampleData: null,
    category: 'DOCUMENT',
  },

  //自賠責等
  {
    jp: '店舗査定_未経過自賠責相当額',
    en: 'unexpiredLiabilityAmount',
    sampleData: null,
    category: 'JIBAN',
  },
  {
    jp: '店舗査定_自賠責保険期間始期日',
    en: 'liabilityInsuranceStartDate',
    type: 'date',
    sampleData: '2022/10/12',
    category: 'JIBAN',
  },
  {
    jp: '店舗査定_自賠責保険期間終期日',
    en: 'liabilityInsuranceEndDate',
    type: 'date',
    sampleData: '2025/11/12',
    category: 'JIBAN',
  },
  {
    jp: '店舗査定_未経過自動車税相当額',
    en: 'unexpiredTaxAmount',
    sampleData: null,
    category: 'JIBAN',
  },

  //リサイクル、シュレッダー、フロンなど
  {
    jp: '店舗査定_車両リサイクル券有無',
    en: 'recyclingCertificate',
    sampleData: 'あり',
    category: 'RECYCLING',
  },
  {
    jp: '店舗査定_車両リサイクル券番号',
    en: 'recyclingCertificateNumber',
    sampleData: '0412-7286-4240',
    category: 'RECYCLING',
  },
  {
    jp: '店舗査定_車両シュレッダーダスト料金',
    en: 'shredderDustFee',
    sampleData: '12000',
    category: 'RECYCLING',
  },
  {
    jp: '店舗査定_車両エアバック類料金',
    en: 'airbagFee',
    sampleData: '2800',
    category: 'RECYCLING',
  },
  {
    jp: '店舗査定_車両フロン類料金',
    en: 'freonFee',
    sampleData: '0',
    category: 'RECYCLING',
  },
  {
    jp: '店舗査定_車両情報管理料金',
    en: 'infoManagementFee',
    sampleData: '130',
    category: 'RECYCLING',
  },
  {
    jp: '店舗査定_車両預りリサイクル預託金',
    en: 'recyclingDeposit',
    sampleData: '14930',
    category: 'RECYCLING',
  },

  //装備品等
  {
    jp: '店舗査定_輸入仕入区分',
    en: 'importCategory',
    sampleData: '国産車',
    category: 'BODY_INFO',
  },
  {
    jp: '店舗査定_ボディタイプ区分',
    en: 'bodyType',
    sampleData: 'ワゴン',
    category: 'BODY_INFO',
  },
  {
    jp: '店舗査定_駆動式名称',
    en: 'driveType',
    sampleData: 'E-Four',
    category: 'BODY_INFO',
  },
  {
    jp: '店舗査定_ミッション名称',
    en: 'transmissionType',
    sampleData: 'AT',
    category: 'BODY_INFO',
    showIn: {
      qrCreate: {label: 'ミッション名称'},
    },
  },
  {
    jp: '店舗査定_ハンドル',
    en: 'steering',
    sampleData: '右',
    category: 'BODY_INFO',
  },
  {
    jp: '店舗査定_ドア車型名',
    en: 'doorType',
    sampleData: '5W',
    category: 'BODY_INFO',
  },
  {
    jp: '店舗査定_寒冷地仕様区分',
    en: 'coldWeatherSpec',
    sampleData: 'なし',
    category: 'BODY_INFO',
  },
  {
    jp: '店舗査定_外装色名',
    en: 'exteriorColor',
    sampleData: 'ﾊﾟｰﾙ',
    category: 'BODY_INFO',
  },
  {
    jp: '店舗査定_カラーコード',
    en: 'colorCode',
    sampleData: '90',
    category: 'BODY_INFO',
  },
  {
    jp: '店舗査定_カラー名称',
    en: 'colorName',
    sampleData: 'ﾌﾟﾚｼｬｽﾎﾜｲﾄﾊﾟｰﾙ',
    category: 'BODY_INFO',
  },
  {
    jp: '店舗査定_内装色名',
    en: 'interiorColor',
    sampleData: 'ブラック',
    category: 'BODY_INFO',
  },

  //修復歴等
  {
    jp: '店舗査定_修復歴問診結果',
    en: 'repairHistory',
    sampleData: '修復歴なし',
    category: 'REPAIR',
  },
  {
    jp: '店舗査定_走行距離_KM換算_',
    en: 'mileageKm',
    sampleData: '24500',
    category: 'REPAIR',
  },
  {
    jp: '店舗査定_メーター交換',
    en: 'meterReplacement',
    sampleData: null,
    category: 'REPAIR',
  },
  {
    jp: '店舗査定_総走行距離値',
    en: 'totalMileage',
    sampleData: null,
    category: 'REPAIR',
  },
  {
    jp: '店舗査定_輸入車区分',
    en: 'importVehicle',
    sampleData: null,
    category: 'REPAIR',
  },

  //装備品
  {
    jp: '店舗査定_モデルイヤー',
    en: 'modelYearDetail',
    sampleData: 'なし',
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_サンルーフ_ムーンルーフ',
    en: 'sunroofMoonroof',
    sampleData: 'ｵｰﾄｴｱｺﾝ',
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_フロントエアコン',
    en: 'frontAc',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_リヤエアコン',
    en: 'rearAc',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_パワーステアリング',
    en: 'powerSteering',
    sampleData: 'なし',
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_パワーウィンドウ',
    en: 'powerWindow',
    sampleData: '本革',
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_ABS',
    en: 'abs',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_電動スライドドア',
    en: 'electricSlideDoor',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_シート素材',
    en: 'seatMaterial',
    sampleData: 'ﾌﾙｾｸﾞ',
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_エアバック料金',
    en: 'airbagFeeDetail',
    sampleData: 'なし',
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_カーナビ_DA',
    en: 'carNaviDa',
    sampleData: 'あり',
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_TV ',
    en: 'tv',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_後席モニター',
    en: 'rearMonitor',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_バックモニター',
    en: 'backMonitor',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_CD',
    en: 'cd',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_DVD',
    en: 'dvd',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_メディアプレーヤー接続',
    en: 'mediaPlayer',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_リヤエンタメ',
    en: 'rearEntertainment',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_マークレビンソン',
    en: 'markLevinson',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_エアロ_スポイラー_',
    en: 'aeroSpoiler',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_アルミホィール',
    en: 'aluminumWheel',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_クルーズコントロール',
    en: 'cruiseControl',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_横滑防止装置',
    en: 'skidControl',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_イモビライザー',
    en: 'immobilizer',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_パワーシート',
    en: 'powerSeat',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_フルフラット',
    en: 'fullFlat',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_ベンチシート',
    en: 'benchSeat',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_3列以上シート',
    en: 'threeRowSeat',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_１_2列名ウォークスルー',
    en: 'walkThrough',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_ローダウン',
    en: 'lowDown',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_ヘッドランプ',
    en: 'headlamp',
    sampleData: 'LED',
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_キーレスエントリー',
    en: 'keylessEntry',
    sampleData: 'ｽﾏｰﾄｷ-',
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_リモコンスターター',
    en: 'remoteStarter',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_ETC',
    en: 'etc',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_ワンオーナー',
    en: 'oneOwner',
    sampleData: null,
    category: 'EQUIPMENT',
  },
  {
    jp: '店舗査定_試乗車',
    en: 'testDrive',
    sampleData: null,
    category: 'EQUIPMENT',
  },

  // 先進装備
  {
    jp: '店舗査定_アクティブスタビライザー',
    en: 'activeStabilizer',
    sampleData: null,
    category: 'ADVANCED_EQUIPMENT',
  },
  {
    jp: '店舗査定_衝突回避_被害軽減',
    en: 'collisionAvoidance',
    sampleData: 'あり',
    category: 'ADVANCED_EQUIPMENT',
  },
  {
    jp: '店舗査定_ペダル踏み間違い',
    en: 'pedalMisstep',
    sampleData: null,
    category: 'ADVANCED_EQUIPMENT',
  },
  {
    jp: '店舗査定_車線逸脱',
    en: 'laneDeparture',
    sampleData: null,
    category: 'ADVANCED_EQUIPMENT',
  },
  {
    jp: '店舗査定_先進ライト',
    en: 'advancedLight',
    sampleData: null,
    category: 'ADVANCED_EQUIPMENT',
  },
  {
    jp: '店舗査定_ブラインドスポットモニター',
    en: 'blindSpotMonitor',
    sampleData: null,
    category: 'ADVANCED_EQUIPMENT',
  },
  {
    jp: '店舗査定_パノラミックビューモニター',
    en: 'panoramicViewMonitor',
    sampleData: null,
    category: 'ADVANCED_EQUIPMENT',
  },
  {
    jp: '店舗査定_ドラレコ',
    en: 'driveRecorder',
    sampleData: null,
    category: 'ADVANCED_EQUIPMENT',
  },
  {
    jp: '店舗査定_アイドリング',
    en: 'idling',
    sampleData: null,
    category: 'ADVANCED_EQUIPMENT',
  },
  {
    jp: '店舗査定_コンセント',
    en: 'outlet',
    sampleData: null,
    category: 'ADVANCED_EQUIPMENT',
  },

  //追加装備
  {
    jp: '店舗査定_追加装備１',
    en: 'additionalEquipment1',
    sampleData: '衝突回避装置_あり_',
    category: 'ADDITIONAL_EQUIPMENT',
  },
  {
    jp: '店舗査定_追加装備２',
    en: 'additionalEquipment2',
    sampleData: 'ディスプレイ_モニター__純正_',
    category: 'ADDITIONAL_EQUIPMENT',
  },
  {
    jp: '店舗査定_追加装備３',
    en: 'additionalEquipment3',
    sampleData: 'ナビ_その他_',
    category: 'ADDITIONAL_EQUIPMENT',
  },
  {
    jp: '店舗査定_追加装備４',
    en: 'additionalEquipment4',
    sampleData: 'デジタルインナーミラー_純正_',
    category: 'ADDITIONAL_EQUIPMENT',
  },
  {
    jp: '店舗査定_追加装備５',
    en: 'additionalEquipment5',
    sampleData: 'なし',
    category: 'ADDITIONAL_EQUIPMENT',
  },
  {
    jp: '店舗査定_EVフラグ',
    en: 'evFlag',
    sampleData: 'なし',
    category: 'ADDITIONAL_EQUIPMENT',
  },
  {
    jp: '店舗査定_REフラグ',
    en: 'reFlag',
    sampleData: 'AAC',
    category: 'ADDITIONAL_EQUIPMENT',
  },
  {
    jp: '店舗査定_エアコン',
    en: 'ac',
    sampleData: 'なし',
    category: 'ADDITIONAL_EQUIPMENT',
  },
  {
    jp: '店舗査定_ナビ',
    en: 'navi',
    sampleData: 'あり',
    category: 'ADDITIONAL_EQUIPMENT',
  },
  {
    jp: '店舗査定_TV _1',
    en: 'tv2',
    sampleData: 'あり',
    category: 'ADDITIONAL_EQUIPMENT',
  },
  {
    jp: '店舗査定_革',
    en: 'leather',
    sampleData: 'なし',
    category: 'ADDITIONAL_EQUIPMENT',
  },
  {
    jp: '店舗査定_SR',
    en: 'sr',
    sampleData: 'あり',
    category: 'ADDITIONAL_EQUIPMENT',
  },
  {
    jp: '店舗査定_アルミ',
    en: 'aluminum',
    sampleData: 'あり',
    category: 'ADDITIONAL_EQUIPMENT',
  },

  // 査定実施情報
  {
    jp: '査定実施日時',
    en: 'assessmentdatetime',
    type: 'date',
    sampleData: '2024/08/27 10:43:58',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '下取買取区分',
    en: 'tradeInPurchaseCategory',
    sampleData: '下取',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '引取予定年月日',
    en: 'pickupScheduledDate',
    type: 'date',
    sampleData: '2025/08/27',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '依頼元販売店名',
    en: 'requestingName',
    sampleData: '',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '依頼元販売店コード',
    en: 'requestingCode',
    sampleData: '',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '査定実施店舗名',
    en: 'assessmentname',
    sampleData: '本社本部',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '査定実施店舗コード',
    en: 'assessmentcode',
    sampleData: '98',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '査定実施スタッフ名',
    en: 'assessmentStaffName',
    sampleData: '川之上 誠',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '査定実施スタッフコード',
    en: 'assessmentStaffCode',
    sampleData: '821091@16301',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '担当営業店舗名',
    en: 'salesname',
    sampleData: '本社本部',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '担当営業店舗コード',
    en: 'salescode',
    sampleData: '98',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '担当営業スタッフ名',
    en: 'salesStaffName',
    sampleData: '川之上 誠',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '担当営業スタッフコード',
    en: 'salesStaffCode',
    sampleData: '821091@16301',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '購入予定車',
    en: 'plannedPurchaseVehicle',
    sampleData: 'ヴェルファイア',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '残価割賦最終回日',
    en: 'residualValueInstallmentFinalDate',
    type: 'date',
    sampleData: '',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '残価割賦最終回支払額',
    en: 'residualValueInstallmentFinalAmount',
    sampleData: '',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '緊急度ステータス',
    en: 'urgencyStatus',
    sampleData: '至急',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '値付担当への連絡事項',
    en: 'valuationContactNotes',
    sampleData: '',
    category: 'ASSESSMENT_IMPLEMETATION',
  },
  {
    jp: '値付依頼日時',
    en: 'valuationRequestDatetime',
    type: 'date',
    sampleData: '2024/08/27 10:43:58',
    category: 'ASSESSMENT_IMPLEMETATION',
  },

  // 査定評価
  {
    jp: '店舗査定_総合評価点',
    en: 'comprehensiveEvaluationScore',
    sampleData: '6',
    category: 'ASSESSMENT_RESULT',
  },
  {
    jp: '査定加減点合計',
    en: 'assessmentAdjustmentPointsTotal',
    sampleData: '',
    category: 'ASSESSMENT_RESULT',
  },
  {
    jp: '店舗査定_新車価格_税抜_',
    en: 'newCarPriceExcludingTax',
    sampleData: '5181',
    category: 'ASSESSMENT_RESULT',
  },

  // 査定価格・調整金額
  {
    jp: '査定価格_円_',
    en: 'assessmentPrice',
    sampleData: '4377',
  },
  {
    jp: '調整金額合計_円_',
    en: 'adjustmentAmountTotal',
    sampleData: '0',
  },
  {
    jp: '調整金額１ 金額_円_',
    en: 'adjustmentAmount1',
    sampleData: '0',
  },
  {
    jp: '調整金額１ 備考',
    en: 'adjustmentAmount1Notes',
    sampleData: '',
  },
  {
    jp: '調整金額２ 金額_円_',
    en: 'adjustmentAmount2',
    sampleData: '0',
  },
  {
    jp: '調整金額２ 備考',
    en: 'adjustmentAmount2Notes',
    sampleData: '',
  },
  {
    jp: '調整金額３ 金額_円_',
    en: 'adjustmentAmount3',
    sampleData: '0',
  },
  {
    jp: '調整金額３ 備考',
    en: 'adjustmentAmount3Notes',
    sampleData: '',
  },
  {
    jp: '調整金額４ 金額_円_',
    en: 'adjustmentAmount4',
    sampleData: '',
  },
  {
    jp: '調整金額５ 金額_円_',
    en: 'adjustmentAmount5',
    sampleData: '',
  },
  {
    jp: '決裁価格_円_',
    en: 'approvedPrice',
    sampleData: '4377',
  },
  {
    jp: '店舗査定_回答価格_円_',
    en: 'assessmentResponsePrice',
    sampleData: '',
  },
  {
    jp: '入庫査定_回答価格_円_',
    en: 'inventoryAssessmentResponsePrice',
    sampleData: '',
  },
  {
    jp: '査定誤差_円_',
    en: 'assessmentError',
    sampleData: '',
  },
  {
    jp: '値付け備考_メモ',
    en: 'valuationNotesMemo',
    sampleData: '',
  },
  {
    jp: '販売価格メモ',
    en: 'salesPriceMemo',
    sampleData: '',
  },
  {
    jp: '営業スタッフへの連絡事項',
    en: 'salesStaffContactNotes',
    sampleData: '',
  },

  // 担当者情報
  {
    jp: '値付担当店舗名',
    en: 'valuationStoreName',
    sampleData: '本社本部',
  },
  {
    jp: '値付担当店舗コード',
    en: 'valuationcode',
    sampleData: '98',
  },
  {
    jp: '値付担当名',
    en: 'valuationName',
    sampleData: '川之上 誠',
  },
  {
    jp: '値付担当社員コード',
    en: 'valuationEmployeeCode',
    sampleData: '821091@16301',
  },
  {
    jp: '入庫検査担当店舗名',
    en: 'inspectioName',
    sampleData: '',
  },
  {
    jp: '入庫検査担当店舗コード',
    en: 'inspectioncode',
    sampleData: '',
  },
  {
    jp: '入庫価格担当店舗名',
    en: 'pricingStoreName',
    sampleData: '',
  },
  {
    jp: '入庫価格担当店舗コード',
    en: 'pricecode',
    sampleData: '',
  },
  {
    jp: '入庫検査担当名',
    en: 'inspectionname',
    sampleData: '',
  },
  {
    jp: '入庫検査担当名コード',
    en: 'inspectionNameCode',
    sampleData: '',
  },
  {
    jp: '入庫価格担当名',
    en: 'pricingPersonName',
    sampleData: '',
  },
  {
    jp: '入庫価格担当名コード',
    en: 'pricingPersonCode',
    sampleData: '',
  },

  // 日時情報
  {
    jp: '値付回答登録日時',
    en: 'valuationResponsedatetime',
    type: 'date',
    sampleData: '2025/07/25 16:40:45',
  },
  {
    jp: '値付開始時間',
    en: 'valuationStarttime',
    type: 'date',
    sampleData: '2025-07-25 16:40:29',
  },
  {
    jp: '値付終了時間',
    en: 'valuationEndtime',
    type: 'date',
    sampleData: '2025-07-25 16:40:45',
  },
  {
    jp: '値付所要時間',
    en: 'valuationRequiredtime',
    sampleData: '16',
  },
  {
    jp: '価格確定日時',
    en: 'priceConfirmationdatetime',
    sampleData: '',
  },
  {
    jp: '入庫査定確定日',
    en: 'inventoryAssessmentConfirmationdate',
    sampleData: '',
  },

  // 履歴情報
  {
    jp: '前回値付番号',
    en: 'previousValuationnumber',
    sampleData: '',
  },
  {
    jp: '前回査定番号',
    en: 'previousAssessmentnumber',
    sampleData: '',
  },
  {
    jp: 'CPO区分',
    en: 'cpoCategory',
    sampleData: '',
  },
]

// {
//   "dealerName": "P岡山",
//   "dealerCode": "16301",
//   "assessmentMode": "店舗査定",
//   "assessmentMode2": "",
//   "status": "回答済",
//   "valuationType": "集中値付",
//   "valuationNumber": "163012408000008",
//   "sateiID": "163012408000017",
//   "palAssessmentNumber": "",
//   "landAffairsName": "倉敷",
//   "registrationClassNumber": "330",
//   "registrationKana": "ひ",
//   "registrationSerialNumber": "1625",
//   "registrationDate": "2022-10-13 07:00:00",
//   "firstRegistrationDate": "202210",
//   "modelYear": "3",
//   "modelYearType": "B",
//   "chassisNumber": "AZSH35-4002743",
//   "frameNumber": "undefined",
//   "brandName": "ﾄﾖﾀ",
//   "modelName": "ｸﾗｳﾝ_ｸﾛｽｵｰﾊﾞｰ_",
//   "ai21ModelCode": "A14F27",
//   "grade": "2.5 CROSSOVER G“Advanced･Leather Package\"",
//   "type": "6AA-AZSH35",
//   "commonType": "AZSH35-AEXMB_I_",
//   "engineType": "A25A-3NM-4NM",
//   "vehicleHistory": "自家用",
//   "capacityMin": "5",
//   "capacityMax": "0",
//   "maxLoad": "0",
//   "weight": "1790",
//   "grossWeight": "2065",
//   "length": "493",
//   "width": "184",
//   "height": "154",
//   "displacement": "2500",
//   "fuelName": "ﾊｲﾌﾞﾘｯﾄﾞ",
//   "typeDesignationNumber": "20467",
//   "categoryNumber": "40",
//   "ownerName": "岡山トヨペット株式会社",
//   "userName": "實石 賢二",
//   "useOwnershipSameFlag": "",
//   "ai21CustomerCode": "221000152",
//   "customerName": "實石 賢二",
//   "customerKanaSurname": "ミイシ",
//   "customerKanaName": "ケンジ",
//   "inspectionExpiryDate": "2025-10-12 07:00:00",
//   "odometerDisplayValue": "",
//   "newCarWarranty": "あり",
//   "maintenanceManual": "あり",
//   "instructionManual": "あり",
//   "periodicInspectionRecord": "",
//   "unexpiredLiabilityAmount": "",
//   "liabilityInsuranceStartDate": "2022-10-12 07:00:00",
//   "liabilityInsuranceEndDate": "2025-11-12 08:00:00",
//   "unexpiredTaxAmount": "",
//   "recyclingCertificate": "あり",
//   "recyclingCertificateNumber": "0412-7286-4240",
//   "shredderDustFee": "12000",
//   "airbagFee": "2800",
//   "freonFee": "0",
//   "infoManagementFee": "130",
//   "recyclingDeposit": "14930",
//   "importCategory": "国産車",
//   "bodyType": "ワゴン",
//   "driveType": "E-Four",
//   "transmissionType": "AT",
//   "steering": "右 ",
//   "doorType": "5W",
//   "coldWeatherSpec": "なし",
//   "exteriorColor": "ﾊﾟｰﾙ",
//   "colorCode": "90",
//   "colorName": "ﾌﾟﾚｼｬｽﾎﾜｲﾄﾊﾟｰﾙ",
//   "interiorColor": "ブラック",
//   "repairHistory": "修復歴なし",
//   "mileageKm": "24500",
//   "meterReplacement": "",
//   "totalMileage": "",
//   "importVehicle": "",
//   "modelYearDetail": "",
//   "sunroofMoonroof": "なし",
//   "frontAc": "ｵｰﾄｴｱｺﾝ",
//   "rearAc": "",
//   "powerSteering": "",
//   "powerWindow": "",
//   "abs": "",
//   "electricSlideDoor": "なし",
//   "seatMaterial": "本革",
//   "airbagFeeDetail": "",
//   "carNaviDa": "",
//   "tv": "undefined",
//   "rearMonitor": "なし",
//   "backMonitor": "あり",
//   "cd": "",
//   "dvd": "",
//   "mediaPlayer": "",
//   "rearEntertainment": "",
//   "markLevinson": "",
//   "aeroSpoiler": "なし",
//   "aluminumWheel": "純正",
//   "cruiseControl": "",
//   "skidControl": "",
//   "immobilizer": "",
//   "powerSeat": "あり",
//   "fullFlat": "",
//   "benchSeat": "",
//   "threeRowSeat": "なし",
//   "walkThrough": "",
//   "lowDown": "",
//   "headlamp": "LED",
//   "keylessEntry": "ｽﾏｰﾄｷ-",
//   "remoteStarter": "",
//   "etc": "",
//   "oneOwner": "",
//   "testDrive": "",
//   "activeStabilizer": "",
//   "collisionAvoidance": "",
//   "pedalMisstep": "",
//   "laneDeparture": "",
//   "advancedLight": "",
//   "blindSpotMonitor": "",
//   "panoramicViewMonitor": "あり",
//   "driveRecorder": "",
//   "idling": "",
//   "outlet": "",
//   "additionalEquipment1": "",
//   "additionalEquipment2": "衝突回避装置_あり_",
//   "additionalEquipment3": "ディスプレイ_モニター__純正_",
//   "additionalEquipment4": "ナビ_その他_",
//   "additionalEquipment5": "デジタルインナーミラー_純正_",
//   "evFlag": "なし",
//   "reFlag": "なし",
//   "ac": "AAC",
//   "navi": "なし",
//   "tv2": "undefined",
//   "leather": "あり",
//   "sr": "なし",
//   "aluminum": "あり",
//   "assessmentdatetime": "2024-08-27 17:43:58",
//   "tradeInPurchaseCategory": "下取",
//   "pickupScheduledDate": "2025-08-27 07:00:00",
//   "requestingName": "",
//   "requestingCode": "",
//   "assessmentname": "本社本部",
//   "assessmentcode": "98",
//   "assessmentStaffName": "川之上 誠",
//   "assessmentStaffCode": "821091@16301",
//   "salesname": "本社本部",
//   "salescode": "98",
//   "salesStaffName": "川之上 誠",
//   "salesStaffCode": "821091@16301",
//   "plannedPurchaseVehicle": "ヴェルファイア",
//   "residualValueInstallmentFinalDate": "",
//   "residualValueInstallmentFinalAmount": "",
//   "urgencyStatus": "至急",
//   "valuationContactNotes": "",
//   "valuationRequestDatetime": "2024-08-27 17:43:58",
//   "comprehensiveEvaluationScore": "6",
//   "assessmentAdjustmentPointsTotal": "",
//   "newCarPriceExcludingTax": "5181",
//   "assessmentPrice": "4377",
//   "adjustmentAmountTotal": "0",
//   "adjustmentAmount1": "0",
//   "adjustmentAmount1Notes": "",
//   "adjustmentAmount2": "0",
//   "adjustmentAmount2Notes": "",
//   "adjustmentAmount3": "0",
//   "adjustmentAmount3Notes": "",
//   "adjustmentAmount4": "",
//   "adjustmentAmount5": "",
//   "approvedPrice": "",
//   "assessmentResponsePrice": "4377",
//   "inventoryAssessmentResponsePrice": "",
//   "assessmentError": "",
//   "valuationNotesMemo": "",
//   "salesPriceMemo": "",
//   "salesStaffContactNotes": "",
//   "valuationStoreName": "本社本部",
//   "valuationcode": "98",
//   "valuationName": "川之上 誠",
//   "valuationEmployeeCode": "821091@16301    ",
//   "inspectioName": "",
//   "inspectioncode": "",
//   "pricingStoreName": "",
//   "pricecode": "",
//   "inspectionname": "",
//   "inspectionNameCode": "",
//   "pricingPersonName": "",
//   "pricingPersonCode": "",
//   "valuationResponsedatetime": "2025-07-25 23:40:45",
//   "valuationStarttime": "2025-07-25 23:40:29",
//   "valuationEndtime": "2025-07-25 23:40:45",
//   "valuationRequiredtime": "16",
//   "priceConfirmationdatetime": "",
//   "inventoryAssessmentConfirmationdate": "",
//   "previousValuationnumber": "",
//   "previousAssessmentnumber": "",
//   "cpoCategory": ""
// }
